<?php
	echo "<font color=black face='Georgia'>";

	echo "<b>";
	echo "<h2>";
	echo "<center>";
	echo "Biodata";
	echo "</h2>";
	echo "<br>";
	echo "<hr>";

	echo "<center>";
	echo "<table width='500' border='0'>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Nama";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Tri Santiana Dewi";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Nama Panggilan";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Tri";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Tempat, Tanggal Lahir";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Ponorogo, 03 September 2001";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Alamat";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Ds. Simo, Kec. Slahung, Ponorogo";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Asal Sekolah";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "SMKN 1 PONOROGO";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Agama";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Islam";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp";
			echo "</td>";
			echo "<td>";
				echo "Jenis Kelamin";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "Perempuan";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Email";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "trisantiana9@gmail.com";
			echo "</td>";
		echo "</tr>";
		echo "</table>";
		echo "<hr>";








?>